"use client";

import React from 'react';
import { ShoppingCart, Package, UserPlus, Star, Clock } from 'lucide-react';
import { formatDateTime } from '@/lib/utils';
import { Activity } from '@/types';

interface ActivityFeedProps {
  activities: Activity[];
}

export default function ActivityFeed({ activities }: ActivityFeedProps) {
  const getActivityIcon = (type: string) => {
    switch (type) {
      case 'order':
        return {
          icon: ShoppingCart,
          color: '#00BFFF',
          bg: 'rgba(0, 191, 255, 0.08)',
        };
      case 'product':
        return {
          icon: Package,
          color: '#9EFF00',
          bg: 'rgba(158, 255, 0, 0.08)',
        };
      case 'customer':
        return {
          icon: UserPlus,
          color: '#FF922B',
          bg: 'rgba(255, 146, 43, 0.08)',
        };
      case 'review':
        return {
          icon: Star,
          color: '#FFD43B',
          bg: 'rgba(255, 212, 59, 0.08)',
        };
      default:
        return {
          icon: Clock,
          color: '#A0A0A0',
          bg: 'rgba(160, 160, 160, 0.08)',
        };
    }
  };

  return (
    <div 
      className="glass-card-static p-5 border flex flex-col gap-4 h-full"
      style={{ borderColor: 'var(--border-color)' }}
    >
      <div>
        <h3 className="text-sm font-bold uppercase tracking-wider text-white">
          System Activity Log
        </h3>
        <p className="text-xs" style={{ color: 'var(--text-secondary)' }}>
          Real-time operations log generated by admin and client-side actions.
        </p>
      </div>

      <div className="flex flex-col gap-4 overflow-y-auto max-h-[350px] pr-2">
        {activities.map((act) => {
          const config = getActivityIcon(act.type);
          const Icon = config.icon;

          return (
            <div key={act.id} className="flex gap-3.5 items-start text-xs border-b border-white/5 pb-3 last:border-0 last:pb-0">
              <div 
                className="w-8 h-8 rounded-lg flex items-center justify-center border shrink-0"
                style={{ 
                  borderColor: `${config.color}15`, 
                  background: config.bg,
                  color: config.color 
                }}
              >
                <Icon size={15} />
              </div>
              <div className="flex-1 min-w-0">
                <p className="font-semibold text-white leading-relaxed break-words">
                  {act.message}
                </p>
                <span className="text-[10px] mt-1 block flex items-center gap-1 font-semibold" style={{ color: 'var(--text-muted)' }}>
                  <Clock size={10} />
                  {formatDateTime(act.timestamp)}
                </span>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
